# Logan Christopher
# CLC1085
# Lab 1 - ASCII Art

print('Initials:')
print()

print('|****************/////////////****************|')
print('*                                             *')
print('*   * - - - *       *             * - - - *   *')
print('*   |               |             |           *')
print('*   |               |             |           *')
print('*   |               |             |           *')
print('*   |               |             |           *')
print('*   * - - - *       * - - - *     * - - - *   *')
print('*                                             *')
print('|****************/////////////****************|')

print()
print()
print()
print()

print('House:')
print()

print('     | ')
print('     \ ')
print('     / ')
print('     \ ')
print('    /|\         / \ ')
print('   /|||\       /   \ ')
print('   |\|/|      /     \ ')
print('   |/|\|     /       \ ')
print('   \|||/    /         \ ')
print('    \|/    /           \ ')
print('    | |   /             \ ')
print('    | |  /               \ ')
print('    | | /                 \ ')
print('    |  /                   \ ')
print('    | /                     \ ')
print('    |/                       \ ')
print('  __/_________________________\_________')
print('  |                           |  /     |')
print('  |    ___                    | /      |')
print('  |   |_|_|                   |/       |')
print('  |   |_|_|                   |        |')
print('  |                    ____   |        |')
print('  |                   | __ |  |        |')
print('  |                   ||__||  |        |')
print('  |                   |    |  |        |')
print('  |___________________|____|__|________|')

print()
print()
print()
print()

print('Animal:')
print()

print('                       _ _ _ _ _ _ _ _ _ _ _ _ _ ')
print('                     _|                         | ')
print('                    |     _                     | ')
print('                    |    |_|                    | ')
print('                    |                           | ')
print('                    |           _ _ _ _ _ _ _ _ |')
print('                    |          |_ _ _ _ _ _')
print('                 _ _|           _ _ _ _ _ |')
print('  _            _|              |')
print(' | |         _|                |_ _')
print(' | |_    _ _|                   _  |')
print(' |   |__|                      | |_|')
print(' |                             |')
print(' |_          RAWR              |')
print('   |_                         _|')
print('     |_                     _|')
print('       |_                 _|')
print('         |_        _     |')
print('           |     _| |_   |')
print('           |   _|     |  |')
print('           |  |_      |  |_')
print('           |_ _ |     |_ _ |')
